-- MySQL Script generated by MySQL Workbench
-- mar 03 mar 2015 06:51:35 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlec` DEFAULT CHARACTER SET utf8 ;
USE `controlec` ;

-- -----------------------------------------------------
-- Table `controlec`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`state` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`town` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `town_name` VARCHAR(45) NOT NULL,
  `state_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `city_state_id_fkey_idx` (`state_id` ASC),
  CONSTRAINT `city_state_id_fkey`
    FOREIGN KEY (`state_id`)
    REFERENCES `controlec`.`state` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`district` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `district_name` VARCHAR(45) NOT NULL,
  `state_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `district_state_id_fkey_idx` (`state_id` ASC),
  CONSTRAINT `district_state_id_fkey`
    FOREIGN KEY (`state_id`)
    REFERENCES `controlec`.`state` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`settling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`settling` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `settling_name` VARCHAR(45) NOT NULL,
  `town_id` BIGINT NOT NULL,
  `district_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `settling_town_id_fkey_idx` (`town_id` ASC),
  INDEX `settling_district_id_fkey_idx` (`district_id` ASC),
  CONSTRAINT `settling_town_id_fkey`
    FOREIGN KEY (`town_id`)
    REFERENCES `controlec`.`town` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `settling_district_id_fkey`
    FOREIGN KEY (`district_id`)
    REFERENCES `controlec`.`district` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`app_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `photo_filename` TEXT NULL,
  `first_names` VARCHAR(45) NOT NULL,
  `last_names` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `phone` VARCHAR(14) NOT NULL,
  `user_type` TINYINT NOT NULL COMMENT '1. Administrador \n2. Coordinador\n3. Supervisor\n4. Representante de casilla\n5. Político\n',
  `settling_id` BIGINT NOT NULL,
  `town_id` BIGINT NOT NULL,
  `state_id` BIGINT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `is_active` BIT NOT NULL DEFAULT 1,
  `access_token` VARCHAR(32) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `access_token_expiration` DATETIME NOT NULL,
  `last_sync` BIGINT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `user_city_id_fkey_idx` (`town_id` ASC),
  INDEX `user_locality_id_fkey_idx` (`settling_id` ASC),
  INDEX `user_state_id_idx` (`state_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `app_user_town_id_fkey`
    FOREIGN KEY (`town_id`)
    REFERENCES `controlec`.`town` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `app_user_settling_id_fkey`
    FOREIGN KEY (`settling_id`)
    REFERENCES `controlec`.`settling` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `app_user_state_id`
    FOREIGN KEY (`state_id`)
    REFERENCES `controlec`.`state` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`meeting` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `place` VARCHAR(200) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `start_date` DATETIME NOT NULL,
  `create_date` DATETIME NOT NULL,
  `last_sync` BIGINT NULL,
  `app_user_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `meeting_app_user_id_fkey_idx` (`app_user_id` ASC),
  CONSTRAINT `meeting_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`alarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`alarm` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `last_sync` BIGINT NULL,
  `app_user_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `alarm_app_user_id_fkey_idx` (`app_user_id` ASC),
  CONSTRAINT `alarm_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`news` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`box`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`box` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `box_name` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `responsible` VARCHAR(100) NOT NULL,
  `district_id` BIGINT NOT NULL,
  `settling_id` BIGINT NOT NULL,
  `town_id` BIGINT NOT NULL,
  `state_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `box_citi_id_fkey_idx` (`town_id` ASC),
  INDEX `box_locality_id_fkey_idx` (`settling_id` ASC),
  INDEX `box_state_id_fkey_idx` (`state_id` ASC),
  INDEX `box_district_id_fkey_idx` (`district_id` ASC),
  CONSTRAINT `box_town_id_fkey`
    FOREIGN KEY (`town_id`)
    REFERENCES `controlec`.`town` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `box_settling_id_fkey`
    FOREIGN KEY (`settling_id`)
    REFERENCES `controlec`.`settling` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `box_state_id_fkey`
    FOREIGN KEY (`state_id`)
    REFERENCES `controlec`.`state` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `box_district_id_fkey`
    FOREIGN KEY (`district_id`)
    REFERENCES `controlec`.`district` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`votes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `political_party` VARCHAR(100) NOT NULL,
  `total` BIGINT NOT NULL,
  `box_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `votes_box_id_idx` (`box_id` ASC),
  CONSTRAINT `votes_box_id`
    FOREIGN KEY (`box_id`)
    REFERENCES `controlec`.`box` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`election_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`election_period` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `election_status` TINYINT NULL COMMENT '1. En campaña\n2. Votaciones\n',
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`meeting_supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`meeting_supervisor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `meeting_id` BIGINT NOT NULL,
  `app_user_id` BIGINT NOT NULL,
  `assistance_promise` BIT NULL,
  `assistance_confirmation` BIT NULL,
  `assistance_estimated` INT NULL,
  `total_assistance` INT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  INDEX `meeting_supervisor_meeting_id:fkey_idx` (`meeting_id` ASC),
  INDEX `meeting_supervisor_app_user_id_fkey_idx` (`app_user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `meeting_supervisor_meeting_id:fkey`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `controlec`.`meeting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `meeting_supervisor_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`news_attached_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`news_attached_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `filename` TEXT NOT NULL,
  `news_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `news_attached_files_news_id_fkey_idx` (`news_id` ASC),
  CONSTRAINT `news_attached_file_news_id_fkey`
    FOREIGN KEY (`news_id`)
    REFERENCES `controlec`.`news` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`alarm_attached_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`alarm_attached_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `filename` TEXT NOT NULL,
  `alarm_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `alarm_attached_files_alarm_id_fkey_idx` (`alarm_id` ASC),
  CONSTRAINT `alarm_attached_file_alarm_id_fkey`
    FOREIGN KEY (`alarm_id`)
    REFERENCES `controlec`.`alarm` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`material` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`material_attached_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`material_attached_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `material_id` BIGINT NOT NULL,
  `filename` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `material_attached_file_material_id_fk_idx` (`material_id` ASC),
  CONSTRAINT `material_attached_file_material_id_fk`
    FOREIGN KEY (`material_id`)
    REFERENCES `controlec`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`chat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `chat_name` VARCHAR(45) NOT NULL,
  `is_global` BIT NOT NULL DEFAULT 0,
  `is_private` BIT NOT NULL DEFAULT 0,
  `last_sync` BIGINT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`chat_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`chat_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `message` TEXT NOT NULL,
  `sent_time` DATETIME NOT NULL,
  `received_time` DATETIME NULL,
  `app_user_id` BIGINT NULL,
  `chat_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `chat_message_app_user_id_fkey_idx` (`app_user_id` ASC),
  INDEX `chat_message_chat_id_fkey_idx` (`chat_id` ASC),
  CONSTRAINT `chat_message_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chat_message_chat_id_fkey`
    FOREIGN KEY (`chat_id`)
    REFERENCES `controlec`.`chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`chat_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`chat_member` (
  `chat_id` BIGINT NOT NULL,
  `app_user_id` BIGINT NOT NULL,
  INDEX `chat_member_chat_id_fkey_idx` (`chat_id` ASC),
  INDEX `chat_member_app_user_id_fkey_idx` (`app_user_id` ASC),
  CONSTRAINT `chat_member_chat_id_fkey`
    FOREIGN KEY (`chat_id`)
    REFERENCES `controlec`.`chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chat_member_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`chat_attached_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`chat_attached_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `chat_message_id` BIGINT NOT NULL,
  `material_id` BIGINT NULL,
  `meeting_id` BIGINT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `chat_attached_file_material_id_fkey_idx` (`material_id` ASC),
  INDEX `chat_attached_file_meeting_file_idx` (`meeting_id` ASC),
  INDEX `chat_attached_file_chat_message_id_fkey_idx` (`chat_message_id` ASC),
  CONSTRAINT `chat_attached_file_material_id_fkey`
    FOREIGN KEY (`material_id`)
    REFERENCES `controlec`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chat_attached_file_meeting_file`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `controlec`.`meeting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chat_attached_file_chat_message_id_fkey`
    FOREIGN KEY (`chat_message_id`)
    REFERENCES `controlec`.`chat_message` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`candidate_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`candidate_information` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `youtube` VARCHAR(45) NULL,
  `political_party` VARCHAR(45) NOT NULL,
  `total_votes` BIGINT NULL,
  `app_user_id` BIGINT NOT NULL,
  `row_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - Non deleted\n1 - Deleted',
  PRIMARY KEY (`id`),
  INDEX `candidate_information_app_user_id_fkey_idx` (`app_user_id` ASC),
  CONSTRAINT `candidate_information_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`app_user_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`app_user_device` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app_user_id` BIGINT NOT NULL,
  `device_id` VARCHAR(100) NOT NULL,
  `is_allowed` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `app_user_device_app_user_id_fkey_idx` (`app_user_id` ASC),
  CONSTRAINT `app_user_device_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`login_history` (
  `app_user_id` BIGINT NOT NULL,
  `app_user_device_id` BIGINT NOT NULL,
  `login_time` DATETIME NOT NULL,
  INDEX `login_history_app_user_id_fkey_idx` (`app_user_id` ASC),
  INDEX `login_history_app_user_device_id_fkey_idx` (`app_user_device_id` ASC),
  CONSTRAINT `login_history_app_user_id_fkey`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `login_history_app_user_device_id_fkey`
    FOREIGN KEY (`app_user_device_id`)
    REFERENCES `controlec`.`app_user_device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlec`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlec`.`comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `app_user_id` BIGINT NOT NULL,
  `alarm_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `app_user_id`, `alarm_id`),
  INDEX `fk_comment_app_user1_idx` (`app_user_id` ASC),
  INDEX `fk__alarm1_idx` (`alarm_id` ASC),
  CONSTRAINT `fk_comment_app_user1`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `controlec`.`app_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__alarm1`
    FOREIGN KEY (`alarm_id`)
    REFERENCES `controlec`.`alarm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'endorgroup' IDENTIFIED BY '3nd0rgr0up';

GRANT ALL ON `controlec`.* TO 'endorgroup';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
